# Generated by Django 6.0.5 on 2026-05-18 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_product_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
