# Generated by Django 6.0.5 on 2026-05-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_delete_order_delete_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='mess',
            new_name='message',
        ),
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
